[tool.poetry]
name = "fakenos"
version = "0.1.0"
description = "Fake Network Operating System"
authors = ["Denis Mulyalin <d.mulyalin@gmail.com>"]
maintainers = ["Denis Mulyalin <d.mulyalin@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["NetworkAutomation", "Testing"]
classifiers = [
    "Topic :: Utilities",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[tool.poetry.dependencies]
python = ">=3.6.5,<3.10"
paramiko = "^2.10.3"

[tool.poetry.dev-dependencies]
pytest = { version = "^7.1.1", markers = "python_version >= '3.7'" }
bandit = "1.7.*"
black = "22.3.*"
flake8 = "4.0.*"
pre-commit = "2.15.*"
pyenchant = "3.2.*"
pylint = "2.12.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
